### PR TITLE
Sockpress Route Class

### PR DESCRIPTION
**Pull request by stevokk**
Okay so I have added a **Route** class (Not Router as we discussed) as I feel this better describes the differences between the express.Router and this single Route class. I also feel that this will then allow a Router class to be added in future if needed and that can use these Route classes with very minimal changes. (Express router works this way: https://github.com/expressjs/express/tree/master/lib/router)

Let me know if you want me to change anything.

Thanks

### CODE REVIEW

**Comment by Lesterpig** [comment]
Thank you very much for this amazing work :)

I'll review it as soon as possible, probably this week-end!

**Comment by stevokk** [comment]
No problem, thank you for the initial work that allowed us to implement sockets so easily!

**Comment by Lesterpig** [comment]
Merged in https://github.com/Lesterpig/sockpress/commit/c3f53acf3f6ff6c98b2e71ec47a574f21e6e5355

I fixed some missing semi-colon and updated the README, leaving the code intact.
Thank you again, your work is released in sockpress@1.1.0 :grinning:

**Comment by stevokk** [comment]
Brilliant, thanks a lot.

**Pull request closed without merging**
