### PR TITLE
fixed namespaces not getting session information

### PR DESCRIPTION
**Pull request by stevokk**
When using routes you wouldn't get the session information on the socket as middleware in socket.io seems to only relate to the route that it was added to.

The tests did not cover this scenario and that's why it has gone undetected.

### CODE REVIEW

**Comment by Lesterpig** [comment]
Woa it's a pretty huge diff! I will check and review your request ASAP, thx.

**Comment by Lesterpig** [comment]
I'm ok with this. Could you write a test for this fix? If not, I'll do it next week.
I'll probably also clean the code before pushing `0.0.6`

**Comment by stevokk** [comment]
@Lesterpig I'm away for the next 10 days but can look into learning mocha and making a test when I get back if you've not got round to it. 

Sorry about the diff formatting, the fork was a product of messing with your library to see how socket.io worked with namespaces. There may also be more performant ways of doing what I've done so don't hesitate to change it.

Thanks for the quick response, once I've got further progress I may clean up and publish some more changes that align the declaration style closer to the Express 4 router if you're interested.

**Comment by Lesterpig** [comment]
Thanks for your work :-)

Mocha is really simple, and pretty interesting (jasmine test format). 

I'll be very happy to see further improvements for this module. Don't hesitate to polish things! I'll try to check this PR and merge it in a clean way when ready :-)

**Comment by stevokk** [comment]
@Lesterpig I have commited two more changes that should intercept when namespaces are first known to try and register before any other middleware has been added. 

This was a bug I was seeing yesterday in my wrapper class, as you know I'm AFK for the next 10 days so I'm stuck with the github editor for the time being. Please be careful before merging anything as diffs are most likely formatted differently by their online editor.

Another option is to stop this pull request and wait until I am able to produce a cleaner version of these changes.

**Comment by Lesterpig** [comment]
Yeah, I think it would be better to close this PR, clean it (rebase) and submit it again. You're doing a lot of hard (and amazing) work in the module, but not easy to understand in the various commits.

It will be a pleasure to merge this work, as soon as tests pass on it ;)
Just waiting for you, tell me if I can do anything.

**Comment by stevokk** [comment]
Agreed, will do when I'm back from holiday including some tests.

**Pull request closed without merging**
