### PR TITLE
Fixed session access from within a namespace

### PR DESCRIPTION
**Pull request by stevokk**
Hello, 

Same fix as https://github.com/Lesterpig/sockpress/pull/6

I've rebased to a single commit and altered a test so that it accesses the session data, writing a separate test seemed wasted as the idea of sockpress is to allow for session sharing.

Test is now passing for me after these code changes.

### CODE REVIEW

**Comment by Lesterpig** [comment]
Thank you again for your work !

I'll review that and add some test cases tomorrow. This PR must absolutely be merged into the module ;-)

**Comment by Lesterpig** [comment]
Will be published as `0.0.6` soon

**Comment by stevokk** [comment]
Brilliant, good to see such an active maintainer!

**Comment by Lesterpig** [comment]
;-)

I've just published the version as `1.0.0` (stable enough I think !)

**Pull request merged**
